#!/usr/bin/env node
/**
 * Renders every icon raster from ONE source of truth.
 *
 * Why this exists: the favicon PNGs used to be hand-maintained and hand-listed
 * in layout.tsx. UI-100 restyled the app and regenerated public/logos, but the
 * tab favicons were missed and kept their opaque WHITE corners for another five
 * releases — the exact defect the redesign set out to fix. Anything derived is
 * now derived here, so a palette change can't leave one file behind.
 *
 * Run: node scripts/gen-icons.mjs   (guarded by src/__tests__/favicon-ships.test.ts)
 */
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

// The Midnight ground. Rasters can't carry a media query, so they commit to the
// dark ground — it reads as deliberate on a light tab bar and disappears into a
// dark one. Never white. src/app/icon.svg stays theme-aware for browsers that
// take SVG favicons.
const GROUND = '#101014';
const PAPER = '#FAF7EF'; // light-theme ground — SVG only; rasters can't switch
const COIN = '#D9A521';
const COIN_EDGE = '#8A6D0B';
const MARK = '#221A04';

/** The coin, full-bleed on its own ground. `radius` is in the 64-unit viewBox. */
const source = (radius) => `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <rect width="64" height="64" rx="${radius}" fill="${GROUND}"/>
  <circle cx="32" cy="32" r="21" fill="${COIN}"/>
  <circle cx="32" cy="32" r="21" fill="none" stroke="${COIN_EDGE}" stroke-width="2"/>
  <path d="M41 26A11 11 0 1 0 41 38" fill="none" stroke="${MARK}" stroke-width="5.5" stroke-linecap="round"/>
</svg>`;

/**
 * At 16px a 14/64 radius eats the mark and leaves the corner ambiguous, which is
 * how a rounded tile starts reading as a white box again. Small sizes go square;
 * the host rounds them itself.
 */
const radiusFor = (size) => (size <= 32 ? 0 : 14);

async function png(size) {
  return sharp(Buffer.from(source(radiusFor(size))))
    .resize(size, size)
    .flatten({ background: GROUND }) // fills the rounded corners — nothing bleeds through
    .ensureAlpha(1) // keep a fully-opaque alpha channel: ICO decoders require RGBA
    .png({ compressionLevel: 9 })
    .toBuffer();
}

/**
 * Minimal ICO container. Vista+ reads PNG-encoded entries verbatim, so this is a
 * 6-byte directory plus one 16-byte record per size — no extra dependency for a
 * format we write once.
 */
function ico(entries) {
  const dir = Buffer.alloc(6 + entries.length * 16);
  dir.writeUInt16LE(0, 0); // reserved
  dir.writeUInt16LE(1, 2); // type: icon
  dir.writeUInt16LE(entries.length, 4);

  let offset = dir.length;
  entries.forEach(({ size, data }, i) => {
    const at = 6 + i * 16;
    dir.writeUInt8(size >= 256 ? 0 : size, at); // 0 means 256
    dir.writeUInt8(size >= 256 ? 0 : size, at + 1);
    dir.writeUInt8(0, at + 2); // palette size (0 = truecolor)
    dir.writeUInt8(0, at + 3); // reserved
    dir.writeUInt16LE(1, at + 4); // colour planes
    dir.writeUInt16LE(32, at + 6); // bits per pixel
    dir.writeUInt32LE(data.length, at + 8);
    dir.writeUInt32LE(offset, at + 12);
    offset += data.length;
  });

  return Buffer.concat([dir, ...entries.map((e) => e.data)]);
}

const FAVICON_SIZES = [16, 32, 48, 64];
const LOGO_SIZES = [128, 256, 512, 1024];
const ICO_SIZES = [16, 32, 48];

const written = [];

for (const size of FAVICON_SIZES) {
  const out = join(root, `public/favicons/favicon-${size}x${size}.png`);
  writeFileSync(out, await png(size));
  written.push(out);
}

for (const size of LOGO_SIZES) {
  const out = join(root, `public/logos/icon-${size}x${size}.png`);
  writeFileSync(out, await png(size));
  written.push(out);
}

const icoOut = join(root, 'src/app/favicon.ico');
writeFileSync(icoOut, ico(await Promise.all(ICO_SIZES.map(async (size) => ({ size, data: await png(size) })))));
written.push(icoOut);

// The SVG favicon is the one format that can follow the tab bar's theme, so it
// keeps its media query — but it is emitted from the same constants as the
// rasters above, so the two can never drift into different-looking coins.
const svgOut = join(root, 'src/app/icon.svg');
writeFileSync(
  svgOut,
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64">
  <!-- Generated by scripts/gen-icons.mjs — edit that, not this. Full-bleed
       ground (never a white corner box) that follows the browser theme. -->
  <style>
    .ground { fill: ${PAPER}; }
    @media (prefers-color-scheme: dark) { .ground { fill: ${GROUND}; } }
  </style>
  <rect class="ground" width="64" height="64" rx="14"/>
  <circle cx="32" cy="32" r="21" fill="${COIN}"/>
  <circle cx="32" cy="32" r="21" fill="none" stroke="${COIN_EDGE}" stroke-width="2"/>
  <path d="M41 26A11 11 0 1 0 41 38" fill="none" stroke="${MARK}" stroke-width="5.5" stroke-linecap="round"/>
</svg>
`
);
written.push(svgOut);

for (const f of written) console.log('wrote', f.replace(`${root}/`, ''));
