"""Pure-logic tests for the Monarch sync — no network, no Firestore, no cloud deps.

Run:  python3 -m pytest functions-sync/test_sync.py
 or:  python3 -m unittest discover -s functions-sync
"""
import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import sync_core as sc  # noqa: E402


class ImportKeyPort(unittest.TestCase):
    """Byte-for-byte against the TS implementation. Expected ids were generated by
    running CSVImportModal.importKey verbatim under node."""

    CASES = [
        (("2026-07-21", -23.54, "Customized Cash Rewards Visa Signature (...3572)",
          "IC INSTACART", 0),
         "imp_2026-07-21%7C-23.54%7C3572%7Cic%20instacart%7C0"),
        (("2026-07-22", 830, "Adv SafeBalance Banking (...2126)",
          "Zelle Transfer Conf# 99CQ7S8TN; BHUVANESWAR REDDY MARREDDY", 0),
         "imp_2026-07-22%7C830.00%7C2126%7Czelle%20transfer%20conf%23%2099cq7s8tn"
         "%3B%20bhuvaneswar%20reddy%20marreddy%7C0"),
        # No last-4 in the label -> falls back to trimmed+lowered label; whitespace
        # collapses; occurrence participates.
        (("2026-07-22", -500, "Apple Card", "  Bill   Payment ", 1),
         "imp_2026-07-22%7C-500.00%7Capple%20card%7Cbill%20payment%7C1"),
        (("2026-07-12", 6.99, "Discover it Card (...4363)",
          "INTERNET PAYMENT - THANK YOU", 0),
         "imp_2026-07-12%7C6.99%7C4363%7Cinternet%20payment%20-%20thank%20you%7C0"),
        # -0 must render "0.00" (JS toFixed) and UTF-8 percent-encodes like JS.
        (("2026-07-01", -0.0, "TOTAL CHECKING (...7535)", "Café — test", 0),
         "imp_2026-07-01%7C0.00%7C7535%7Ccaf%C3%A9%20%E2%80%94%20test%7C0"),
        (("2026-07-13", -11.28, "Blue Cash Preferred® (...1001)",
          "ANTHROPIC  SAN FRANCISCO CA", 2),
         "imp_2026-07-13%7C-11.28%7C1001%7Canthropic%20san%20francisco%20ca%7C2"),
    ]

    def test_byte_for_byte(self):
        for args, expected in self.CASES:
            self.assertEqual(sc.import_key(*args), expected, args)

    def test_to_fixed_2(self):
        self.assertEqual(sc.to_fixed_2(-0.0), "0.00")
        self.assertEqual(sc.to_fixed_2(830), "830.00")
        self.assertEqual(sc.to_fixed_2(-85.5), "-85.50")

    def test_twin_label(self):
        # App account with last-4 -> the key component the CSV label produced.
        key = sc.import_key("2026-07-20", -5.0,
                            sc.twin_label({"lastFourDigits": "2126"}, "Adv SafeBalance Banking"),
                            "X", 0)
        self.assertIn("%7C2126%7C", key)
        # No last-4 -> Monarch display name, lowered, like "Apple Card" was.
        key = sc.import_key("2026-07-20", -5.0,
                            sc.twin_label({}, "Apple Card"), "X", 0)
        self.assertIn("%7Capple%20card%7C", key)


def mk(amount, category="Shopping", merchant="Amazon", plaid="AMZN MKTPL", notes="",
       date="2026-07-24", **over):
    t = {"id": "123", "amount": amount, "date": date, "pending": False,
         "plaidName": plaid, "notes": notes,
         "category": {"name": category}, "merchant": {"name": merchant},
         "account": {"id": "a1", "displayName": "Adv SafeBalance Banking"}}
    t.update(over)
    return t


class TxnMapping(unittest.TestCase):
    def test_expense(self):
        r = sc.map_txn(mk(-23.54, category="Groceries", merchant="Instacart",
                          plaid="IC INSTACART"))
        self.assertEqual(r["type"], "expense")
        self.assertEqual(r["amount"], 23.54)
        self.assertEqual(r["signed"], -23.54)
        self.assertEqual(r["title"], "Instacart")          # title = merchant, like the CSV
        self.assertEqual(r["sourceCategory"], "Groceries")  # verbatim
        self.assertEqual(r["category"], "food")             # mapCategory('groceries')
        self.assertEqual(r["description"], "IC INSTACART")  # plaidName first
        self.assertIsNone(r["transferDirection"])

    def test_income(self):
        r = sc.map_txn(mk(4309.93, category="Paychecks", merchant="The Canton Co"))
        self.assertEqual(r["type"], "income")
        self.assertEqual(r["category"], "other")  # 'Paychecks' maps to no expense bucket

    def test_transfer_in_out(self):
        r = sc.map_txn(mk(700.0, category="Credit Card Payment", merchant="Bank of America"))
        self.assertEqual((r["type"], r["transferDirection"]), ("transfer", "in"))
        r = sc.map_txn(mk(-500.0, category="Transfer", merchant="Zelle"))
        self.assertEqual((r["type"], r["transferDirection"]), ("transfer", "out"))

    def test_transfer_fee_is_not_a_transfer(self):
        r = sc.map_txn(mk(-5.0, category="Transfer Fee"))
        self.assertEqual(r["type"], "expense")

    def test_loan_autodetect_forces_expense(self):
        # Mirrors parseCSV: a title containing upstart/loan/sofi/lending is forced
        # to expense/'other' even when the amount is an inflow.
        r = sc.map_txn(mk(1000.0, category="Other", merchant="Upstart"))
        self.assertEqual((r["type"], r["category"]), ("expense", "other"))

    def test_description_precedence_plaid_notes_none(self):
        self.assertEqual(sc.map_txn(mk(-1.0, plaid="", notes="hand note"))["description"],
                         "hand note")
        self.assertIsNone(sc.map_txn(mk(-1.0, plaid="", notes=""))["description"])

    def test_zero_and_missing_rows_dropped(self):
        self.assertIsNone(sc.map_txn(mk(0.0)))
        self.assertIsNone(sc.map_txn(mk(None)))
        self.assertIsNone(sc.map_txn(mk(-1.0, date="")))

    def test_pending_flag_surfaces(self):
        self.assertTrue(sc.map_txn(mk(-1.0, pending=True))["pending"])


class CursorMath(unittest.TestCase):
    def test_first_run_uses_cutover(self):
        self.assertEqual(sc.cursor_start(None), "2026-07-23")
        self.assertEqual(sc.cursor_start(""), "2026-07-23")

    def test_overlap_window(self):
        self.assertEqual(sc.cursor_start("2026-07-30"), "2026-07-25")
        self.assertEqual(sc.cursor_start("2026-08-01"), "2026-07-27")
        # month boundary
        self.assertEqual(sc.cursor_start("2026-08-03"), "2026-07-29")


class BalanceSign(unittest.TestCase):
    def test_debt_stored_positive_owed(self):
        # Monarch reports card debt negative; app stores positive owed.
        self.assertEqual(sc.opening_balance_for("credit_card", -507.96), 507.96)
        self.assertEqual(sc.opening_balance_for("personal_loan", -2068.93), 2068.93)

    def test_bank_kept_as_is(self):
        self.assertEqual(sc.opening_balance_for("bank_account", 829.60), 829.60)

    def test_credit_balance_not_clamped(self):
        # Overpaid card: Monarch positive -> negative owed, kept (spec: do not clamp).
        self.assertEqual(sc.opening_balance_for("credit_card", 25.0), -25.0)


class AccountMatching(unittest.TestCase):
    ACCOUNTS = [
        {"id": "1", "name": "Adv SafeBalance Banking", "lastFourDigits": "2126"},
        {"id": "2", "name": "Apple Card"},
        {"id": "3", "name": "TOTAL CHECKING", "lastFourDigits": "7535"},
    ]

    def test_mask_wins(self):
        self.assertEqual(sc.match_account("Renamed Account", "2126", self.ACCOUNTS)["id"], "1")

    def test_name_contains(self):
        self.assertEqual(sc.match_account("Apple Card", None, self.ACCOUNTS)["id"], "2")
        self.assertEqual(sc.match_account("TOTAL CHECKING (...7535)", None, self.ACCOUNTS)["id"], "3")

    def test_unmatched_is_none_never_guessed(self):
        self.assertIsNone(sc.match_account("Vanguard Brokerage", "9999", self.ACCOUNTS))
        self.assertIsNone(sc.match_account("", None, self.ACCOUNTS))


if __name__ == "__main__":
    unittest.main()
